Allow multiple modids to be used in the input of Mod Storage Bus
GlodBlock/ExtendedAE pull request #177
Opened 2024-06-11 16:39 UTC by WexalianMC

This is (finally) the pull request as discussed in #176.

This PR allows the user to input multiple mod ids by seperating them with a comma.
It also updates the suggestions by skipping a suggestion if the modid is already added.

I made this in 1.20.1, but this should be able to get ported to each version without changes, as there are minimal changes to begin with (6 lines in 2 files).

If there are any questions, gladly ask them!

2024-06-12 05:54 UTC, GlodBlock requested changes

2024-06-12 05:54 UTC, GlodBlock commented on src/main/java/com/glodblock/github/extendedae/util/FCClientUtil.java
>              if (mod.startsWith(inputText)) {
you need to remove all characters before the last comma

2024-06-13 17:48 UTC, WexalianMC commented
Alright, should be actually working now

2024-06-14 07:28 UTC, GlodBlock approved these changes
good job

2024-06-14 07:28 UTC, merged